version: '3'
services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop2.7.4-java8
    networks:
      - workbench
    volumes:
      - namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop.env
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      # add placement constraint to allocate namenode on particular server
      placement:
        constraints: 
          - node.role == manager
      labels:
        traefik.docker.network: workbench
        traefik.port: 50070
    ports:
      - 50070:50070
      - 9000:9000

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop2.7.4-java8
    networks:
      - workbench
    volumes:
      - datanode:/hadoop/dfs/data
    env_file:
      - ./hadoop.env
    environment:
      SERVICE_PRECONDITION: "namenode:50070"
    deploy:
      # mode global will deploy one datanode per docker swarm node
      #mode: global
      mode: replicated
      replicas: 3
      restart_policy:
        condition: on-failure
      placement:
        constraints: 
          - node.role == worker
      labels:
        traefik.docker.network: workbench
        traefik.port: 50075
#    ports:
#      - 50075:50075
  
  

volumes:
  datanode:
  namenode:
#  hadoop_historyserver:

networks:
  workbench:
    external: true
